### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by nhoffman**
I think this is ready to release. I don't think that I have access to the pypi or readthedocs accounts, though.

### CODE REVIEW

**Comment by nhoffman** [comment]
@matsen - please just let me know if you're ok with the concept of a python3-only release - no need to go through all of the changes! I'll probably need help with credentials for uploading to pypi and readthedocs, unless @crosenth has them.

**Comment by matsen** [comment]
Noah, this seems great but before I merge could @crosenth cut another release with the very latest 2.7 code? v0.6.2 or so? Then we can have something fixed to point the old-schoolers to.

**Comment by cmccoy** [comment]
Noah (hey!), I think you should have PyPI access:

Package Index Owner: cmccoy, Noah.Hoffman, bcclaywell

**Comment by nhoffman** [comment]
@cmccoy - hey there and thanks! Not quite sure about the docs, though: it's easy enough to update the version on GH pages (https://fhcrc.github.io/seqmagick/), but not sure about https://pythonhosted.org/seqmagick or http://seqmagick.readthedocs.org - it's kind of confusing to have all three! @matsen - any thoughts about which we should maintain?

**Comment by nhoffman** [comment]
@matsen - there doesn't seem to be a tag for 0.6.2 (is this a release or was that a typo?), but a tarball for 0.6.1 is uploaded to pypi. I'll definitely add a note to the README about how to install for python2, and make sure that the old tarball is visible on pypi.

**Comment by matsen** [comment]
I was saying that we _should_ cut a 0.6.2 release, put it on https://github.com/fhcrc/seqmagick/releases and pypi. Gee, seems like the RTD thing is the most up to date, so perhaps we should continue that?

**Comment by nhoffman** [comment]
Got it - I didn't think to see if there were unreleased changes in master. I'll tag whatever is in master as 0.6.2, publish to pypi, and then release 0.7.0. Thanks!

**Comment by nhoffman** [comment]
Ok, I released 0.6.2. Here's the updated readme, which notes how to install using python2.7: https://github.com/fhcrc/seqmagick/blob/python3-nh/README.rst

Pretty sure I'm ready to release 0.7.0 - I can publish tarball to pypi and updated docs to github pages, but I'm not sure how to update docs in other locations.

**Comment by matsen** [comment]
OK, merged. Make a release and I think RTD will update automagically

**Pull request merged**
