### PR TITLE
Protparam

### PR DESCRIPTION
**Pull request by omgwtfgames**
This patch adds a "protparam" command for calculating and sorting a set protein sequences on molecular weight and predicted isoelectric point.

I actually wrote most of this code ~2 years ago for my own use, but forgot to clean it up and send a pull request :P. If this is a feature you'd like to integrate, I can also add some documentation.

(err .. bugger .. sent this pull request while logged into the wrong Github account too ...)

### CODE REVIEW

**Comment by omgwtfgames** [comment]
Yep, good to merge from my end.

**Comment by tillea** [comment]
Any progress on accepting this pull request?

**Comment by matsen** [comment]
Boy, we did drop the ball here.

You really do want this? It seems a bit at odds with the rest of the
utilities in the package.

**Comment by tillea** [comment]
> Boy, we did drop the ball here. You really do want this? It seems a bit at odds with the rest of the utilities in the package.

I just maintain the Debian package of seqmagick and realised that there is a pending user request that might or might not be interesting for Debian users.  I personally do not want this and do not have any opinion on it.

**Comment by matsen** [comment]
There's a debian package???

OK, I'll close this. I don't think it's of general interest.

**Comment by tillea** [comment]
On Wed, Jul 08, 2020 at 02:30:09AM -0700, Erick Matsen wrote:
> There's a debian package???
The Debian Med team is packaging *lots* of bioinformatics stuff:

     https://blends.debian.org/med/tasks/bio#seqmagick

You might like to check out more.  Feel free to mention it in your
install instructions.  May be we need to advertise our work a bit better
...

**Pull request closed without merging**
